# Generated by Django 4.1.7 on 2023-03-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0)),
                ('size', models.FloatField(default=0)),
                ('ratings_count', models.IntegerField(default=0)),
                ('languages', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('industry', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Predictied_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=100)),
                ('application_category', models.CharField(max_length=100)),
            ],
        ),
    ]
