# Generated by Django 4.1.7 on 2023-04-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Buisness', max_length=20)),
                ('prize', models.FloatField(default=0)),
                ('size', models.FloatField(default=0)),
            ],
        ),
    ]
