# Generated by Django 4.1.7 on 2023-03-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appName', models.CharField(max_length=20)),
                ('appStore', models.CharField(max_length=20)),
                ('appCatergory', models.CharField(max_length=20)),
            ],
        ),
    ]
