# Generated by Django 4.1.7 on 2023-03-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_appdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appdetails',
            name='appCatergory',
        ),
        migrations.RemoveField(
            model_name='appdetails',
            name='appName',
        ),
        migrations.RemoveField(
            model_name='appdetails',
            name='appStore',
        ),
        migrations.AddField(
            model_name='appdetails',
            name='languages',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='appdetails',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='appdetails',
            name='ratings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appdetails',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
